### ISSUE TITLE
IDriss CTA

### ISSUE THREAD

**Issue by Riglanto** [Glo-Foundation/glo-wallet#391]
Add a CTA to setup a free IDriss if you hold $100 Glo Dollar. This consists of
- A modal with instructions
- A backend that checks whether a user has $100 Glo Dollar and then sends that wallet address to IDriss for inclusion in their allowlist of 1 free IDriss
- A link to an IDriss hosted flow for the user to claim their free IDriss

**Comment by gglucass** [comment]
@Riglanto For the CTA copy let's do

**Claim free IDriss handle**
Hold $100+ of Glo Dollar to claim an IDriss registration for this wallet

With this icon: https://mirror-media.imgix.net/publication-images/D51AJ4naPXuSXvZokOw5W.png?h=64&w=64

<img width="418" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/b70a8ae2-a20e-45b0-b297-5e5bd066dd4b">

**Comment by gglucass** [comment]
@Riglanto for the modal with instructions let's do

**IDriss 🤝 Glo Dollar**
We've teamed up with IDriss to gift a free registration to community members that own at least $100 Glo Dollars. With an IDriss you can use an  📧, 📱 or @Twitter instead of your wallet address. You can then share your impact using this name: https://app.glodollar.org/impact/@geyr_garmr

Availability is limited, so act fast!

1. Buy $100 Glo Dollars (or more!)
    - Across all blockchains
2. Request a free IDriss registration
     - Just click here 
3. Complete IDriss registration
     - Connect your wallet on idriss.xyz
