### ISSUE TITLE
View all transactions

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#52]
Paginated in a modal?

<img width="274" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/c193e838-bd07-44fe-9fc9-f44641e53d3f">

**Comment by Riglanto** [comment]
Moralis api leverages cursor approach over pagination - https://docs.moralis.io/web3-data-api/reference/get-erc20-transfers?chain=eth&contract_addresses=[]&exclude_contracts=[]&wallet_addresses=[]&exclude_wallets=[]

Perhaps we could add "Load more button" at the bottom instead of pagination, wdyt @gglucass ?
